 version: 2
 jobs: 
   one: 
     docker:
       - image: circleci/node:12
     steps:
       - checkout 
       - run: npm install
   two: 
     steps:
       - run: npm run build:prod
   three: 
     steps:
       - run: npm run deploy

 workflows:
   version: 2
   one_and_two: 
     jobs: 
       - one
       - two
       - three