--- 
jobs: 
  one: 
    docker: 
      - 
        image: "circleci/node:12"
    steps: 
      - checkout
      - 
        run: "npm install"
  three: 
    steps: 
      - 
        run: "npm run deploy"
  two: 
    steps: 
      - 
        run: "npm run build:prod"
version: 2
workflows: 
  filters: 
    branches: 
      only: master
  pipeline: 
    jobs: 
      - one
      - two
      - three
  version: 2
