--- 
jobs: 
  checkout: 
    docker: 
      - image: "circleci/node:12"
    steps: 
      - checkout
      - run: "npm install"
  build: 
    docker: 
      - image: "circleci/node:12"
    steps: 
      - run: "npm run build:prod"
  deploy: 
    docker: 
      - image: "circleci/node:12"
    steps: 
      - run: "npm run deploy"
      
workflows: 
  filters: 
    branches: 
      only: master
  pipeline: 
    jobs: 
      - checkout
        filters: 
          branches: 
           only: master
      - build
        filters: 
          branches: 
           only: master
      - deploy
        filters: 
          branches: 
           only: master
