name: Pipeline

on:
  push:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        github_token: ${{ secrets.ACCESS_TOKEN }}
    - run: npm install
    - run: npm run build-prod
    - run: npm run deploy
